### ISSUE TITLE
Application crashes on invalid value in amount field

### ISSUE THREAD

**Issue by jonasdeluna** [webkom/kvittering#1058]
The value gets saved to sessionStorage on a debounce/timer and upon trying to refresh or waiting long enough the site crashes.
Probably because I tried to input an expressions such as "100+50".

![image](https://github.com/webkom/kvittering/assets/113468143/e6ec8e70-be9e-41d6-8a43-8062e1db6f89)

Browsers tested:
Mercury 123.0.1 (64-bit)
Microsoft Edge Version 126.0.2592.56

**Comment by norbye** [comment]
Nice catch! Tried debugging a little bit and it seems like the form component sets the amount to `undefined` for some reason - possibly because the type is set to number and the + messes that up.

It seems we might have potential to handle those errors a little bit nicer as well(:

**Comment by norbye** [comment]
Resolved in #1126
