### ISSUE TITLE
Delete and view files

### ISSUE THREAD

**Issue by amalieeh** [webkom/kvittering#3]
When you upload files there is no way to delete or se which files that are uploaded.

**Comment by JonasBak** [comment]
It shouldn't be that hard to delete files, just remove the correct index of `this.state.images` in `PictureUpload`. I don't know if there is an easy way of viewing the contents or a thumbnail of the files you have uploaded, but it might be enough to just see the filenames listed.

**Comment by SmithPeder** [comment]
Closed in https://github.com/webkom/kvittering/pull/26
